# Generated by Django 6.0.1 on 2026-01-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
